# Generated by Django 5.2.3 on 2025-07-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_calories_burned_ride_distance_meters'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_calories_burned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_distance_meters',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='total_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
