# Generated by Django 5.2.3 on 2025-07-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_user_total_calories_burned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_address_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_address_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_address_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_address_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_address_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_address_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
